type: object
properties:
  id:
    type: integer
  ids:
    type: array
    items:
      type: integer
  id_empresa:
    type: integer
  sigla_loja:
    type: string
  nome_reduzido:
    type: string
  codigo_sku:
    type: integer
  ucom:
    type: string
  nome_sku:
    type: string
  curva:
    type: integer
  dias_estoq:
    type: integer
  quant_mes:
    type: number
  ticket_mes:
    type: number
  valor_mes:
    type: number
  quant_natural:
    type: number
  sazo_efet:
    type: number
  expo:
    type: integer
  total_sazo:
    type: number
  es_minimo:
    type: integer
  camp:
    type: integer
  cmmf_quant:
    type: number
  cmmf_validade:
    type: string
  pendente_erp:
    type: boolean
  atualizado_erp:
    type: boolean
  ultima_venda:
    type: string
  data_checagem:
    type: string
  encalhado:
    type: boolean
  data_hora:
    type: string
  esmin_padrao:
    type: integer
  capac_aa:
    type: integer
  capac_zz:
    type: integer
  emb_distrib:
    type: integer
  vetor_empresa:
    type: array
    items:
      type: integer
  quant_predio:
    type: number
  capac_predio:
    type: integer
  soma_pedidos:
    type: number
  log_id:
    type: integer
  proj_efet:
    type: number
  observacoes:
    type: string
  url_foto:
    type: string
