type: object
properties:
  id:
    type: integer
  nome_reduzido:
    type: string
  proj:
    type: boolean
  loja:
    type: boolean
  suprim:
    type: boolean
  compra:
    type: boolean
  calendario:
    $ref: ./jsoncalendario.yaml
  dias_semana:
    type: array
    items:
      type: integer
  ips:
    $ref: ./jsonip.yaml
  acesso_restrito:
    type: boolean
  codigo_wms:
    type: integer
  tags_nd:
    type: array
    items:
      type: integer
  id_emp_curva:
    type: integer
  validade_emp_curva:
    type: string
  copiar_curva:
    type: boolean
