type: object
properties:
  id:
    type: integer
  id_canal:
    type: integer
  desc_canal:
    type: string
  preco_minimo:
    type: number
  valor_adicional:
    type: number
  somar_frete:
    type: boolean
  perc_adic_frete:
    type: number
