type: object
properties:
  id:
    type: integer
  ordem:
    type: integer
  id_metrica:
    type: integer
  titulo_indicador:
    type: string
  id_comparativo:
    type: integer
  ids_grupos:
    type: array
    items:
      type: integer
